#!/usr/bin/env python3
"""Generate system colors from the wallpaper (i3, polybar, rofi, dunst, OSD).
Usage: theme.py [--force]   Returns exit code 0 if colors changed, 1 if unchanged."""
import colorsys, hashlib, json, os, sys, glob
from PIL import Image

HOME = os.path.expanduser("~")
CFG = f"{HOME}/.config"
walls = sorted(glob.glob(f"{CFG}/i3/wallpaper.*"))
if not walls: sys.exit(1)
WALL = walls[0]
STAMP = f"{CFG}/i3/.theme-stamp"

digest = hashlib.md5(open(WALL, "rb").read()).hexdigest()
if "--force" not in sys.argv and os.path.exists(STAMP) and open(STAMP).read() == digest:
    sys.exit(1)

img = Image.open(WALL).convert("RGB"); img.thumbnail((240, 240))
pal = img.quantize(colors=12, method=Image.Quantize.MEDIANCUT)
p = pal.getpalette()
counts = sorted(pal.getcolors(), reverse=True)
cols = [(n, tuple(c / 255 for c in p[i*3:i*3+3])) for n, i in counts]
total = sum(n for n, _ in cols)

def hls(c): return colorsys.rgb_to_hls(*c)
def hexc(h, l, s):
    r, g, b = colorsys.hls_to_rgb(h % 1, max(0, min(l, 1)), max(0, min(s, 1)))
    return "#%02x%02x%02x" % (round(r*255), round(g*255), round(b*255))

# base hue = most common color
bh, bl, bs = hls(cols[0][1])
# accent = most saturated, reasonably common, not too dark
def score(item):
    n, c = item; h, l, s = hls(c)
    v = max(c)
    return s * (n / total) ** 0.35 * (0.2 if v < 0.25 else 1)
ah, al, as_ = hls(max(cols, key=score)[1])
if as_ < 0.12:          # grayscale wallpaper -> soft neutral accent
    ah, as_ = bh, 0.25

c = {
    "bg":       hexc(bh, 0.08, min(bs, 0.30)),
    "bg_alt":   hexc(bh, 0.13, min(bs, 0.25)),
    "inactive": hexc(bh, 0.20, min(bs, 0.20)),
    "fg":       hexc(bh, 0.88, min(bs, 0.20)),
    "dim":      hexc(bh, 0.50, min(bs, 0.15)),
    "accent":   hexc(ah, 0.68, max(as_, 0.55)),
    "accent2":  hexc(ah + 0.08, 0.72, max(as_, 0.45)),
    "urgent":   hexc(0.98, 0.68, 0.80),
}

w = lambda path, text: (os.makedirs(os.path.dirname(path), exist_ok=True), open(path, "w").write(text))
w(f"{CFG}/i3/colors.json", json.dumps(c, indent=2))
w(f"{CFG}/i3/colors.conf", f"""# generated by theme.py from the wallpaper
client.focused          {c['accent']} {c['accent']} {c['bg']} {c['accent2']} {c['accent']}
client.focused_inactive {c['inactive']} {c['inactive']} {c['fg']} {c['inactive']} {c['inactive']}
client.unfocused        {c['bg']} {c['bg']} {c['dim']} {c['bg']} {c['bg']}
client.urgent           {c['urgent']} {c['urgent']} {c['bg']} {c['urgent']} {c['urgent']}
client.background       {c['bg']}
""")
w(f"{CFG}/polybar/colors.ini", "[colors]\n" + "".join(f"{k} = {c[k]}\n" for k in ("bg", "fg", "dim", "accent", "urgent")))
w(f"{CFG}/rofi/colors.rasi", "* {\n" + "".join(f"  {k.replace('_','-')}: {v};\n" for k, v in c.items()) + "}\n")
w(f"{CFG}/dunst/dunstrc", f"""# generated by theme.py from the wallpaper
[global]
font = JetBrainsMono Nerd Font 11
width = 340
frame_width = 2
frame_color = "{c['accent']}"
separator_color = frame
corner_radius = 0
padding = 12
horizontal_padding = 14
show_indicators = no
mouse_left_click = do_action, close_current
mouse_middle_click = close_all
mouse_right_click = close_current

[urgency_low]
background = "{c['bg']}"
foreground = "{c['fg']}"
highlight = "{c['accent']}"

[urgency_normal]
background = "{c['bg']}"
foreground = "{c['fg']}"
highlight = "{c['accent']}"

[urgency_critical]
background = "{c['bg']}"
foreground = "{c['urgent']}"
frame_color = "{c['urgent']}"
highlight = "{c['urgent']}"

[wired_sound]
summary = "*"
script = ~/.config/dunst/sound.sh
""")
# KDE/Qt color scheme (kdeglobals) - dark, tinted by the wallpaper
def rgb(h): h = h.lstrip("#"); return ",".join(str(int(h[i:i+2], 16)) for i in (0, 2, 4))
def kde_group(bgn, bga, fgn, fgi):
    return {"BackgroundNormal": rgb(bgn), "BackgroundAlternate": rgb(bga),
            "ForegroundNormal": rgb(fgn), "ForegroundInactive": rgb(fgi), "ForegroundActive": rgb(c["accent"]),
            "ForegroundLink": rgb(c["accent"]), "ForegroundVisited": rgb(c["accent2"]),
            "ForegroundNegative": "218,68,83", "ForegroundNeutral": "246,116,0", "ForegroundPositive": "39,174,96",
            "DecorationFocus": rgb(c["accent"]), "DecorationHover": rgb(c["accent"])}
kde = {
    "Colors:View": kde_group(c["bg"], c["bg_alt"], c["fg"], c["dim"]),
    "Colors:Window": kde_group(c["bg_alt"], c["inactive"], c["fg"], c["dim"]),
    "Colors:Button": kde_group(c["inactive"], c["bg_alt"], c["fg"], c["dim"]),
    "Colors:Selection": {**kde_group(c["accent"], c["accent2"], c["bg"], c["bg"]), "ForegroundActive": rgb(c["bg"])},
    "Colors:Tooltip": kde_group(c["bg"], c["bg_alt"], c["fg"], c["dim"]),
    "Colors:Complementary": kde_group(c["bg"], c["bg_alt"], c["fg"], c["dim"]),
    "Colors:Header": kde_group(c["bg_alt"], c["bg"], c["fg"], c["dim"]),
    "Colors:Header][Inactive": kde_group(c["bg_alt"], c["bg"], c["fg"], c["dim"]),
    "WM": {"activeFont": "JetBrainsMono Nerd Font,10,-1,5,400,0,0,0,0,0,0,0,0,0,0,1", "activeBackground": rgb(c["bg_alt"]), "activeForeground": rgb(c["fg"]),
           "inactiveBackground": rgb(c["bg"]), "inactiveForeground": rgb(c["dim"])},
    "General": {"ColorScheme": "WallpaperDark", "font": "JetBrainsMono Nerd Font,10,-1,5,400,0,0,0,0,0,0,0,0,0,0,1", "fixed": "JetBrainsMono Nerd Font Mono,10,-1,5,400,0,0,0,0,0,0,0,0,0,0,1", "menuFont": "JetBrainsMono Nerd Font,10,-1,5,400,0,0,0,0,0,0,0,0,0,0,1", "smallestReadableFont": "JetBrainsMono Nerd Font,8,-1,5,400,0,0,0,0,0,0,0,0,0,0,1", "toolBarFont": "JetBrainsMono Nerd Font,10,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"},
    "KDE": {"widgetStyle": "Breeze"},
    "Icons": {"Theme": "Papirus-Dark-Wall"},
}
kg = f"{CFG}/kdeglobals"
sections, order, cur = {}, [], None
if os.path.exists(kg):
    for line in open(kg).read().splitlines():
        if line.startswith("[") and line.endswith("]"):
            cur = line[1:-1]; order.append(cur); sections.setdefault(cur, [])
        elif cur is not None and "=" in line:
            sections[cur].append(line.split("=", 1))
for sec, kv in kde.items():
    if sec not in sections: sections[sec] = []; order.append(sec)
    d = dict(sections[sec]); d.update(kv); sections[sec] = [[k, v] for k, v in d.items()]
w(kg, "\n".join(f"[{sec}]\n" + "".join(f"{k}={v}\n" for k, v in sections[sec]) for sec in order))

# fastfetch: render the template with the wallpaper colors
tpl = f"{CFG}/fastfetch/config.template.jsonc"
if os.path.exists(tpl):
    sc = lambda h: ";".join(str(int(h.lstrip("#")[i:i+2], 16)) for i in (0, 2, 4))
    t = open(tpl).read()
    for k, v in {"ACC_RAW": "38;2;" + sc(c["accent"]), "ACC2_RAW": "38;2;" + sc(c["accent2"]),
                 "DIM_RAW": "38;2;" + sc(c["dim"]), "FG_RAW": "38;2;" + sc(c["fg"]),
                 "ACC2": sc(c["accent2"]), "ACC": sc(c["accent"]), "DIM": sc(c["dim"]), "FG": sc(c["fg"]),
                 "BG": sc(c["bg"]), "INACT": sc(c["inactive"])}.items():
        t = t.replace("{{" + k + "}}", v)
    w(f"{CFG}/fastfetch/config.jsonc", t)

# Alacritty: black background, all colors are shades of the accent (a gradient)
S_ = max(0.45, min(0.70, as_ * 0.95))
mono = {            # (hue shift, lightness): same hue family, different tones
    "blue":    (-0.030, 0.52), "red":    (-0.012, 0.60), "magenta": (0.000, 0.68),
    "green":   (+0.015, 0.74), "yellow": (+0.030, 0.80), "cyan":    (+0.020, 0.86),
}
normal = {k: hexc(ah + dh, L, S_) for k, (dh, L) in mono.items()}
bright = {k: hexc(ah + dh, min(L + 0.08, 0.93), S_ * 0.85) for k, (dh, L) in mono.items()}
normal["black"], bright["black"] = hexc(ah, 0.14, 0.12), hexc(ah, 0.45, 0.12)
normal["white"], bright["white"] = hexc(ah, 0.84, 0.10), hexc(ah, 0.95, 0.08)
order = ["black", "red", "green", "yellow", "blue", "magenta", "cyan", "white"]
w(f"{CFG}/alacritty/wallpaper.toml", "# generated by theme.py from the wallpaper\n"
  "[colors.primary]\nbackground = \"#000000\"\nforeground = \"" + c["fg"] + "\"\n\n"
  "[colors.cursor]\ntext = \"#000000\"\ncursor = \"" + c["accent"] + "\"\n\n"
  "[colors.selection]\ntext = \"#000000\"\nbackground = \"" + c["accent"] + "\"\n\n"
  "[colors.search.matches]\nforeground = \"#000000\"\nbackground = \"" + c["accent2"] + "\"\n\n"
  "[colors.normal]\n" + "".join(f'{k} = "{normal[k]}"\n' for k in order) + "\n"
  "[colors.bright]\n" + "".join(f'{k} = "{bright[k]}"\n' for k in order))

# cava: wide bars with a vertical gradient through the terminal palette (dark -> light)
grad = [normal["blue"], normal["red"], normal["magenta"], normal["green"], normal["yellow"], normal["cyan"]]
w(f"{CFG}/cava/config", "; generated by theme.py from the wallpaper (old config: config.bak)\n"
  "[general]\nautosens = 1\nbars = 0\nbar_width = 3\nbar_spacing = 1\nframerate = 60\n\n"
  "[input]\nsource = auto\n\n"
  "[output]\nmethod = noncurses\nchannels = stereo\nmono_option = average\n\n"
  "[color]\ngradient = 1\ngradient_count = " + str(len(grad)) + "\n" +
  "".join(f"gradient_color_{i+1} = '{g}'\n" for i, g in enumerate(grad)) + "\n"
  "[smoothing]\nnoise_reduction = 77\nmonstercat = 0\nwaves = 0\n")

# Telegram Desktop theme (.tdesktop-theme = zip with a color list + chat background)
try:
    import io, zipfile
    from PIL import ImageFilter, ImageEnhance
    B, BA, IN, F, D = c["bg"], c["bg_alt"], c["inactive"], c["fg"], c["dim"]
    A, A2, U = c["accent"], c["accent2"], c["urgent"]
    OUT = hexc(ah, 0.20, min(max(as_, 0.25), 0.45)); OUTS = hexc(ah, 0.27, min(max(as_, 0.25), 0.45))
    OUTD = hexc(ah, 0.62, 0.20)
    tg = {
        "windowBg": B, "windowFg": F, "windowBgOver": BA, "windowBgRipple": IN, "windowFgOver": F,
        "windowSubTextFg": D, "windowSubTextFgOver": D, "windowBoldFg": F, "windowBoldFgOver": F,
        "windowBgActive": A, "windowFgActive": B, "windowActiveTextFg": A, "windowShadowFg": "#000000",
        "windowShadowFgFallback": BA, "shadowFg": "#00000030", "slideFadeOutBg": "#0000003c",
        "activeButtonBg": A, "activeButtonBgOver": A2, "activeButtonBgRipple": A2, "activeButtonFg": B,
        "activeButtonFgOver": B, "activeButtonSecondaryFg": BA, "activeButtonSecondaryFgOver": BA,
        "activeLineFg": A, "activeLineFgError": U,
        "lightButtonBg": B, "lightButtonBgOver": BA, "lightButtonBgRipple": IN, "lightButtonFg": A, "lightButtonFgOver": A,
        "attentionButtonFg": U, "attentionButtonFgOver": U, "attentionButtonBgOver": BA, "attentionButtonBgRipple": IN,
        "outlineButtonBg": B, "outlineButtonBgOver": BA, "outlineButtonOutlineFg": A, "outlineButtonBgRipple": IN,
        "menuBg": BA, "menuBgOver": IN, "menuBgRipple": IN, "menuIconFg": D, "menuIconFgOver": F,
        "menuSubmenuArrowFg": D, "menuFgDisabled": D, "menuSeparatorFg": IN,
        "scrollBarBg": F + "53", "scrollBarBgOver": F + "7a", "scrollBg": F + "1a", "scrollBgOver": F + "2c",
        "smallCloseIconFg": D, "smallCloseIconFgOver": F, "radialFg": A, "radialBg": "#00000056",
        "placeholderFg": D, "placeholderFgActive": D, "inputBorderFg": IN, "filterInputBorderFg": A,
        "filterInputInactiveBg": BA, "filterInputActiveBg": B, "checkboxFg": D, "sliderBgInactive": IN, "sliderBgActive": A,
        "tooltipBg": BA, "tooltipFg": F, "tooltipBorderFg": IN,
        "titleBg": B, "titleBgActive": B, "titleFg": D, "titleFgActive": F, "titleShadow": "#00000000",
        "titleButtonBg": B, "titleButtonFg": D, "titleButtonBgOver": BA, "titleButtonFgOver": F,
        "titleButtonBgActive": B, "titleButtonFgActive": D, "titleButtonBgActiveOver": BA, "titleButtonFgActiveOver": F,
        "trayCounterBg": A, "trayCounterBgMute": IN, "trayCounterFg": B,
        "dialogsBg": B, "dialogsNameFg": F, "dialogsChatIconFg": F, "dialogsDateFg": D, "dialogsTextFg": D,
        "dialogsTextFgService": A, "dialogsDraftFg": U, "dialogsVerifiedIconBg": A, "dialogsVerifiedIconFg": B,
        "dialogsSendingIconFg": D, "dialogsSentIconFg": A, "dialogsUnreadBg": A, "dialogsUnreadBgMuted": IN, "dialogsUnreadFg": B,
        "dialogsBgOver": BA, "dialogsNameFgOver": F, "dialogsDateFgOver": D, "dialogsTextFgOver": D,
        "dialogsBgActive": A, "dialogsNameFgActive": B, "dialogsChatIconFgActive": B, "dialogsDateFgActive": B,
        "dialogsTextFgActive": B, "dialogsTextFgServiceActive": B, "dialogsDraftFgActive": B, "dialogsSentIconFgActive": B,
        "dialogsUnreadBgActive": B, "dialogsUnreadBgMutedActive": BA, "dialogsUnreadFgActive": A,
        "dialogsRippleBg": IN, "dialogsRippleBgActive": A2, "dialogsForwardBg": A, "dialogsForwardFg": B,
        "searchedBarBg": BA, "searchedBarFg": D, "topBarBg": B, "emojiPanBg": BA, "emojiPanCategories": B,
        "emojiPanHeaderFg": D, "emojiPanHeaderBg": BA, "emojiIconFg": D, "emojiIconFgActive": A,
        "historyTextInFg": F, "historyTextOutFg": F, "historyCaptionInFg": F, "historyCaptionOutFg": F,
        "historyFileNameInFg": F, "historyFileNameOutFg": F, "historyOutIconFg": A, "historySendingOutIconFg": OUTD,
        "historyLinkInFg": A, "historyLinkOutFg": A2,
        "msgInBg": BA, "msgInBgSelected": IN, "msgOutBg": OUT, "msgOutBgSelected": OUTS,
        "msgSelectOverlay": A + "40", "msgStickerOverlay": A + "80", "msgInShadow": "#00000000", "msgOutShadow": "#00000000",
        "msgInServiceFg": A, "msgInServiceFgSelected": A, "msgOutServiceFg": A2, "msgOutServiceFgSelected": A2,
        "msgInDateFg": D, "msgInDateFgSelected": D, "msgOutDateFg": OUTD, "msgOutDateFgSelected": OUTD,
        "msgServiceFg": F, "msgServiceBg": B + "b3", "msgServiceBgSelected": BA + "cc",
        "msgFileInBg": A, "msgFileInBgOver": A2, "msgFileOutBg": A2, "msgFileOutBgOver": A,
        "msgWaveformInActive": A, "msgWaveformInInactive": IN, "msgWaveformOutActive": A2, "msgWaveformOutInactive": OUTD,
        "historyComposeAreaBg": B, "historyComposeAreaFg": F, "historyComposeAreaFgService": D,
        "historyComposeIconFg": D, "historyComposeIconFgOver": A, "historySendIconFg": A, "historySendIconFgOver": A2,
        "historyPinnedBg": B, "historyReplyBg": B, "historyReplyIconFg": A, "historyReplyCancelFg": D, "historyReplyCancelFgOver": F,
        "historyComposeButtonBg": B, "historyComposeButtonBgOver": BA, "historyComposeButtonBgRipple": IN,
        "historyToDownBg": BA, "historyToDownBgOver": IN, "historyToDownFg": D, "historyToDownFgOver": F, "historyToDownShadow": "#00000040",
        "historyUnreadBarBg": BA, "historyUnreadBarBorder": IN, "historyUnreadBarFg": A,
        "historyForwardChooseBg": "#0000004c", "historyForwardChooseFg": F, "historyPeerUserpicFg": "#ffffff",
        "sideBarBg": B, "sideBarBgActive": BA, "sideBarBgRipple": IN, "sideBarTextFg": D, "sideBarTextFgActive": A,
        "sideBarIconFg": D, "sideBarIconFgActive": A, "sideBarBadgeBg": A, "sideBarBadgeBgMuted": IN, "sideBarBadgeFg": B,
        "boxBg": B, "boxTextFg": F, "boxTextFgGood": A, "boxTextFgError": U, "boxTitleFg": F, "boxSearchBg": B,
        "boxTitleAdditionalFg": D, "boxTitleCloseFg": D, "boxTitleCloseFgOver": F, "boxDividerBg": BA,
        "introBg": B, "introTitleFg": F, "introDescriptionFg": D, "introErrorFg": U,
        "notificationBg": B, "callBg": B + "f2", "callNameFg": F, "callFingerprintBg": BA, "callStatusFg": D,
        "mediaPlayerBg": B, "mediaPlayerActiveFg": A, "mediaPlayerInactiveFg": IN, "mediaPlayerDisabledFg": D,
        "profileVerifiedCheckBg": A, "profileVerifiedCheckFg": B, "profileAdminStartFg": A,
        "stickerPanDeleteBg": "#000000cc", "stickerPanDeleteFg": F, "stickerPreviewBg": B + "b0",
        "overviewCheckBg": "#00000040", "overviewCheckFg": F, "overviewCheckFgActive": B, "overviewPhotoSelectOverlay": A + "33",
        "reportSpamBg": B, "reportSpamFg": F, "newGroupAboutFg": D, "membersAboutLimitFg": D,
    }
    colors_txt = "// generated by theme.py from the wallpaper\n" + "".join(f"{k}: {v};\n" for k, v in tg.items())
    # chat background: a plain color (a tiny solid tile), same tone as the theme background
    buf = io.BytesIO(); Image.new("RGB", (16, 16), tuple(int(B.lstrip("#")[i:i+2], 16) for i in (0, 2, 4))).save(buf, "PNG")
    os.makedirs(f"{CFG}/i3/telegram", exist_ok=True)
    with zipfile.ZipFile(f"{CFG}/i3/telegram/wired.tdesktop-theme", "w", zipfile.ZIP_DEFLATED) as z:
        z.writestr("colors.tdesktop-theme", colors_txt)
        z.writestr("tiled.png", buf.getvalue())
except Exception as e:
    print("telegram theme:", e, file=sys.stderr)

# Papirus folder colors (overlay theme Papirus-Dark-Wall)
icons = f"{HOME}/.local/share/icons/Papirus-Dark-Wall"
if os.path.isdir(icons):
    st = f"{icons}/.wall-colors.json"
    old = json.load(open(st)) if os.path.exists(st) else {"main": "#ca7287", "light": "#f0d9de"}
    new = {"main": hexc(ah, 0.62, max(as_, 0.50)), "light": hexc(ah, 0.90, max(as_, 0.50) * 0.6)}
    if old != new:
        for f in glob.glob(f"{icons}/*/places/*.svg"):
            if os.path.islink(f): continue
            t = open(f).read()
            t2 = t.replace(old["main"], new["main"]).replace(old["main"].upper(), new["main"]) \
                  .replace(old["light"], new["light"]).replace(old["light"].upper(), new["light"])
            if t2 != t: open(f, "w").write(t2)
        json.dump(new, open(st, "w"))
# lock screen image: wallpaper scaled to the screen, blurred and darkened
try:
    from PIL import ImageFilter, ImageEnhance
    import re as _re
    try:
        import subprocess as _sp
        q = _sp.run(["xrandr", "--query"], capture_output=True, text=True).stdout
    except Exception: q = ""
    m = _re.search(r"current (\d+) x (\d+)", q)
    SW, SH = (int(m.group(1)), int(m.group(2))) if m else (1920, 1080)
    im = Image.open(WALL).convert("RGB")
    k = max(SW / im.width, SH / im.height)
    im = im.resize((round(im.width * k), round(im.height * k)), Image.LANCZOS)
    l, t = (im.width - SW) // 2, (im.height - SH) // 2
    im = im.crop((l, t, l + SW, t + SH)).filter(ImageFilter.GaussianBlur(12))
    ImageEnhance.Brightness(im).enhance(0.45).save(f"{CFG}/i3/lock.png")
except Exception as e:
    print("lock image:", e, file=sys.stderr)
# SDDM login theme "wired": same look as the lock screen; installed once with sudo into
# /usr/share/sddm/themes/wired (owned by you), after that this keeps it in sync with the wallpaper
try:
    import shutil
    src, dst = f"{CFG}/i3/sddm/wired", "/usr/share/sddm/themes/wired"
    conf = "[General]\n" + "".join(f"{k}={c[v]}\n" for k, v in (("bg", "bg"), ("bgalt", "bg_alt"), ("fg", "fg"),
                                    ("dim", "dim"), ("accent", "accent"), ("accent2", "accent2"), ("urgent", "urgent")))
    if os.path.isdir(src): open(f"{src}/theme.conf", "w").write(conf)
    if os.path.isdir(dst) and os.access(dst, os.W_OK):
        for f in ("Main.qml", "metadata.desktop", "theme.conf"): shutil.copy(f"{src}/{f}", f"{dst}/{f}")
        if os.path.exists(f"{CFG}/i3/lock.png"): shutil.copy(f"{CFG}/i3/lock.png", f"{dst}/background.png")
        if not os.path.exists(f"{dst}/font.ttf"):
            for fnt in (f"{HOME}/.local/share/fonts/JetBrainsMonoNerdFont-Regular.ttf", f"{CFG}/i3/fonts/JetBrainsMonoNerdFont-Regular.ttf"):
                if os.path.exists(fnt): shutil.copy(fnt, f"{dst}/font.ttf"); break
        for f in os.listdir(dst): os.chmod(f"{dst}/{f}", 0o644)
except Exception as e:
    print("sddm theme:", e, file=sys.stderr)
open(STAMP, "w").write(digest)
print(json.dumps(c))
sys.exit(0)
